package collection.driver;

/**
 * State is a class representing one of the States that belongs to the United States of America.
 */
public enum State {
  STATES_OUTSIDE_THE_US, ALABAMA, ALASKA, ARIZONA, ARKANSAS, CALIFORNIA, COLORADO,
  CONNECTICUT, DELAWARE, FLORIDA, GEORGIA, HAWAII, IDAHO,
  ILLINOIS, INDIANA, IOWA, KANSAS, KENTUCKY, LOUISIANA, MAINE,
  MARYLAND, MASSACHUSETTS, MICHIGAN, MINNESOTA, MISSISSIPPI,
  MISSOURI, MONTANA, NEBRASKA, NEVADA, NEW_HAMPSHIRE, NEW_JERSEY,
  NEW_MEXICO, NEWYORK, NORTH, CAROLINA, NORTH_DAKOTA, OHIO,
  OKLAHOMA, OREGON, PENNSYLVANIA, RHODE_ISLAND, SOUTH_CAROLINA,
  SOUTH_DAKOTA, TENNESSEE, TEXAS, UTAH, VERMONT, VIRGINIA,
  WASHINGTON, WEST_VIRGINIA, WISCONSIN, WYOMING
}
